import { ThemePreset, ThemeConfig } from '../types';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'default-minimal',
    name: 'Minimal Clean',
    category: 'Minimal',
    customizable: true,
    tagline: 'Clean & Modern',
    badge: 'Popular',
    bgColor: '#FFFFFF',
    bgType: 'solid',
    textColor: '#0F172A',
    headingColor: '#0F172A',
    linkHoverColor: '#4F46E5',
    buttonColor: '#0F172A',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#0F172A',
    buttonStyle: 'solid',
    buttonShape: 'rounded-xl',
    buttonHover: 'scale',
    cardStyle: 'card-white',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'midnight-gradient',
    name: 'Midnight Gradient',
    category: 'Gradient',
    customizable: true,
    tagline: 'Deep dark violet gradient',
    badge: 'Trending',
    bgColor: '#0B0F19',
    bgGradientFrom: '#0B0F19',
    bgGradientTo: '#1E1B4B',
    bgGradientAngle: '135deg',
    bgType: 'gradient',
    textColor: '#F8FAFC',
    headingColor: '#FFFFFF',
    linkHoverColor: '#818CF8',
    buttonColor: '#6366F1',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#6366F1',
    buttonStyle: 'gradient',
    buttonShape: 'rounded-xl',
    buttonHover: 'glow',
    cardStyle: 'card-glass',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    category: 'Warm',
    customizable: true,
    tagline: 'Warm orange and pink tones',
    badge: 'Warm',
    bgColor: '#FFF7ED',
    bgGradientFrom: '#FFEDD5',
    bgGradientTo: '#FCE7F3',
    bgGradientAngle: '135deg',
    bgType: 'gradient',
    textColor: '#1E293B',
    headingColor: '#0F172A',
    linkHoverColor: '#EA580C',
    buttonColor: '#F97316',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#F97316',
    buttonStyle: 'solid',
    buttonShape: 'rounded-full',
    buttonHover: 'lift',
    cardStyle: 'elevated',
    fontFamily: 'Outfit',
    headingFont: 'Outfit',
    bodyFont: 'Outfit',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'emerald-forest',
    name: 'Emerald Forest',
    category: 'Nature',
    customizable: true,
    tagline: 'Deep green and earthy tones',
    badge: 'Nature',
    bgColor: '#064E3B',
    bgGradientFrom: '#064E3B',
    bgGradientTo: '#022C22',
    bgGradientAngle: '180deg',
    bgType: 'gradient',
    textColor: '#ECFDF5',
    headingColor: '#FFFFFF',
    linkHoverColor: '#34D399',
    buttonColor: '#10B981',
    buttonTextColor: '#064E3B',
    buttonBorderColor: '#10B981',
    buttonStyle: 'solid',
    buttonShape: 'rounded-xl',
    buttonHover: 'scale',
    cardStyle: 'glass',
    fontFamily: 'DM Sans',
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
];

export function presetToConfig(preset: ThemePreset, userId: string): ThemeConfig {
  return {
    id: `theme_${Date.now()}`,
    userId,
    presetId: preset.id,
    category: preset.category,
    customizable: preset.customizable,
    tagline: preset.tagline,
    badge: preset.badge,
    bgColor: preset.bgColor,
    bgGradientFrom: preset.bgGradientFrom,
    bgGradientTo: preset.bgGradientTo,
    bgGradientAngle: preset.bgGradientAngle,
    bgType: preset.bgType,
    textColor: preset.textColor,
    headingColor: preset.headingColor,
    linkHoverColor: preset.linkHoverColor,
    buttonColor: preset.buttonColor,
    buttonTextColor: preset.buttonTextColor,
    buttonBorderColor: preset.buttonBorderColor,
    buttonStyle: preset.buttonStyle,
    buttonShape: preset.buttonShape,
    buttonHover: preset.buttonHover,
    cardStyle: preset.cardStyle,
    fontFamily: preset.fontFamily,
    headingFont: preset.headingFont,
    bodyFont: preset.bodyFont,
    baseSize: preset.baseSize,
    fontWeight: preset.fontWeight,
    letterSpacing: preset.letterSpacing,
    stickerPack: preset.stickerPack,
    updatedAt: new Date().toISOString(),
  };
}
