import { ThemePreset, ThemeConfig } from '../types';

export const THEME_PRESETS: ThemePreset[] = [
  // CATEGORY 1 — MINIMAL
  {
    id: 'pure-minimal',
    name: 'Pure Minimal',
    category: 'Minimal',
    customizable: true,
    tagline: 'White canvas with elevated black elements for peak modernism.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FFFFFF',
    bgGradientFrom: '#FFFFFF',
    bgGradientTo: '#FAFAFA',
    bgGradientAngle: 'to-b',
    textColor: '#171717',
    headingColor: '#171717',
    linkHoverColor: '#000000',
    buttonColor: '#171717',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#171717',
    buttonStyle: 'solid',
    buttonShape: 'pill',
    buttonHover: 'lift',
    cardStyle: 'minimal',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'paper',
    name: 'Paper',
    category: 'Minimal',
    customizable: true,
    tagline: 'Warm tactile feel resembling high-end organic cardstock.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FAFAF9',
    bgGradientFrom: '#FAFAF9',
    bgGradientTo: '#F5F5F4',
    bgGradientAngle: 'to-b',
    textColor: '#1C1917',
    headingColor: '#0C0A09',
    linkHoverColor: '#44403C',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#1C1917',
    buttonBorderColor: '#E7E5E4',
    buttonStyle: 'outline',
    buttonShape: 'rounded',
    buttonHover: 'lift',
    cardStyle: 'minimal',
    fontFamily: 'DM Sans',
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    baseSize: 16,
    fontWeight: 'normal',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'mono',
    name: 'Mono',
    category: 'Minimal',
    customizable: true,
    tagline: 'High precision typography with stark grayscale accents.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#F8FAFC',
    bgGradientFrom: '#F8FAFC',
    bgGradientTo: '#F1F5F9',
    bgGradientAngle: 'to-b',
    textColor: '#0F172A',
    headingColor: '#0F172A',
    linkHoverColor: '#000000',
    buttonColor: '#0F172A',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#0F172A',
    buttonStyle: 'solid',
    buttonShape: 'sharp',
    buttonHover: 'underline',
    cardStyle: 'minimal',
    fontFamily: 'Space Grotesk',
    headingFont: 'Space Grotesk',
    bodyFont: 'Space Grotesk',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'tight',
    stickerPack: 'geometric',
  },
  {
    id: 'swiss',
    name: 'Swiss',
    category: 'Minimal',
    customizable: true,
    tagline: 'Stark white with red alerts and tight international style grids.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FFFFFF',
    bgGradientFrom: '#FFFFFF',
    bgGradientTo: '#F8FAFC',
    bgGradientAngle: 'to-b',
    textColor: '#000000',
    headingColor: '#E11D48',
    linkHoverColor: '#E11D48',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#000000',
    buttonBorderColor: '#000000',
    buttonStyle: 'outline',
    buttonShape: 'sharp',
    buttonHover: 'glow',
    cardStyle: 'minimal',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'bold',
    letterSpacing: 'tight',
    stickerPack: 'subtle-lines',
  },

  // CATEGORY 2 — WARM
  {
    id: 'warm-sand',
    name: 'Warm Sand',
    category: 'Warm',
    customizable: true,
    tagline: 'Sun-baked clay and deep terracotta tones for a grounding aura.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FAF6F0',
    bgGradientFrom: '#FAF6F0',
    bgGradientTo: '#FAF6F0',
    bgGradientAngle: 'to-b',
    textColor: '#443A34',
    headingColor: '#2B231F',
    linkHoverColor: '#C2410C',
    buttonColor: '#C2410C',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#C2410C',
    buttonStyle: 'solid',
    buttonShape: 'rounded',
    buttonHover: 'lift',
    cardStyle: 'elevated',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'minimal-dots',
  },
  {
    id: 'peach-glow',
    name: 'Peach Glow',
    category: 'Warm',
    customizable: true,
    tagline: 'Warm amber glow overlaid with frosted glass components.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#FFF7F2',
    bgGradientFrom: '#FFF7F2',
    bgGradientTo: '#FFE8DC',
    bgGradientAngle: 'to-br',
    textColor: '#7C2D12',
    headingColor: '#431407',
    linkHoverColor: '#EA580C',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#7C2D12',
    buttonBorderColor: '#FFD7C2',
    buttonStyle: 'glass',
    buttonShape: 'pill',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Manrope',
    headingFont: 'Manrope',
    bodyFont: 'Manrope',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'caramel',
    name: 'Caramel',
    category: 'Warm',
    customizable: true,
    tagline: 'Rich butterscotch backgrounds matched with deep cocoa brown buttons.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FFFBF5',
    bgGradientFrom: '#FFFBF5',
    bgGradientTo: '#FFFBF5',
    bgGradientAngle: 'to-b',
    textColor: '#5C3D2E',
    headingColor: '#382218',
    linkHoverColor: '#B45309',
    buttonColor: '#8C5A3C',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#8C5A3C',
    buttonStyle: 'solid',
    buttonShape: 'rounded',
    buttonHover: 'lift',
    cardStyle: 'elevated',
    fontFamily: 'DM Sans',
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'amber-halo',
    name: 'Amber Halo',
    category: 'Warm',
    customizable: true,
    tagline: 'Golden ambient lighting paired with amber gradient pills.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FFFBEB',
    bgGradientFrom: '#FFFBEB',
    bgGradientTo: '#FEF3C7',
    bgGradientAngle: 'to-br',
    textColor: '#78350F',
    headingColor: '#451A03',
    linkHoverColor: '#D97706',
    buttonColor: '#D97706',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#D97706',
    buttonStyle: 'gradient',
    buttonShape: 'pill',
    buttonHover: 'shimmer',
    cardStyle: 'elevated',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'geometric',
  },

  // CATEGORY 3 — COOL
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    category: 'Cool',
    customizable: true,
    tagline: 'Refreshing seafoam canvas loaded with rich emerald buttons.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#F2FBF7',
    bgGradientFrom: '#F2FBF7',
    bgGradientTo: '#DCFCE7',
    bgGradientAngle: 'to-b',
    textColor: '#064E3B',
    headingColor: '#022C22',
    linkHoverColor: '#059669',
    buttonColor: '#059669',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#059669',
    buttonStyle: 'solid',
    buttonShape: 'pill',
    buttonHover: 'lift',
    cardStyle: 'minimal',
    fontFamily: 'Manrope',
    headingFont: 'Manrope',
    bodyFont: 'Manrope',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'ice-crystal',
    name: 'Ice Crystal',
    category: 'Cool',
    customizable: true,
    tagline: 'Glacial arctic gradient met with navy frosted glass panels.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#F0F9FF',
    bgGradientFrom: '#F0F9FF',
    bgGradientTo: '#E0F2FE',
    bgGradientAngle: 'to-b',
    textColor: '#0C4A6E',
    headingColor: '#082F49',
    linkHoverColor: '#0284C7',
    buttonColor: '#0369A1',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#0369A1',
    buttonStyle: 'glass',
    buttonShape: 'rounded',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'normal',
    letterSpacing: 'normal',
    stickerPack: 'subtle-lines',
  },
  {
    id: 'sky-motion',
    name: 'Sky Motion',
    category: 'Cool',
    customizable: true,
    tagline: 'Weightless atmospheric blue with deep cyan active gradients.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#FFFFFF',
    bgGradientFrom: '#F0F9FF',
    bgGradientTo: '#E0F2FE',
    bgGradientAngle: 'to-br',
    textColor: '#0369A1',
    headingColor: '#075985',
    linkHoverColor: '#0284C7',
    buttonColor: '#0284C7',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#0284C7',
    buttonStyle: 'gradient',
    buttonShape: 'pill',
    buttonHover: 'lift',
    cardStyle: 'minimal',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'lagoon-deep',
    name: 'Lagoon Deep',
    category: 'Cool',
    customizable: true,
    tagline: 'Deep tranquil seafoam matched with solid deep teal buttons.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#F0FDFA',
    bgGradientFrom: '#F0FDFA',
    bgGradientTo: '#CCFBF1',
    bgGradientAngle: 'to-br',
    textColor: '#134E4A',
    headingColor: '#042F2E',
    linkHoverColor: '#0D9488',
    buttonColor: '#0F766E',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#0F766E',
    buttonStyle: 'solid',
    buttonShape: 'rounded',
    buttonHover: 'lift',
    cardStyle: 'elevated',
    fontFamily: 'DM Sans',
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'geometric',
  },

  // CATEGORY 4 — GRADIENT
  {
    id: 'indigo-motion',
    name: 'Indigo Motion',
    category: 'Gradient',
    customizable: true,
    tagline: 'Calm twilight background coupled with bright violet actions.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#EEF2FF',
    bgGradientFrom: '#EEF2FF',
    bgGradientTo: '#E0E7FF',
    bgGradientAngle: 'to-br',
    textColor: '#1E1B4B',
    headingColor: '#312E81',
    linkHoverColor: '#4F46E5',
    buttonColor: '#4F46E5',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#4F46E5',
    buttonStyle: 'gradient',
    buttonShape: 'rounded',
    buttonHover: 'glow',
    cardStyle: 'minimal',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'sunset-glass',
    name: 'Sunset Glass',
    category: 'Gradient',
    customizable: true,
    tagline: 'Sunkissed crimson gradients housing beautifully backlit glass pills.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#FFF7ED',
    bgGradientFrom: '#FFF7ED',
    bgGradientTo: '#FFE4E6',
    bgGradientAngle: 'to-br',
    textColor: '#881337',
    headingColor: '#4C0519',
    linkHoverColor: '#E11D48',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#881337',
    buttonBorderColor: '#FECDD3',
    buttonStyle: 'glass',
    buttonShape: 'pill',
    buttonHover: 'glass',
    cardStyle: 'minimal',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    category: 'Gradient',
    customizable: true,
    tagline: 'Boreal forest lights transitioning from violet into fresh green.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#F5F3FF',
    bgGradientFrom: '#F5F3FF',
    bgGradientTo: '#DCFCE7',
    bgGradientAngle: 'to-tr',
    textColor: '#4C1D95',
    headingColor: '#2E1065',
    linkHoverColor: '#7C3AED',
    buttonColor: '#7C3AED',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#7C3AED',
    buttonStyle: 'gradient',
    buttonShape: 'rounded',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Manrope',
    headingFont: 'Manrope',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'neon-mist',
    name: 'Neon Mist',
    category: 'Gradient',
    customizable: true,
    tagline: 'White mist overlaid with glowing neon cyan elements.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FAF5FF',
    bgGradientFrom: '#FAF5FF',
    bgGradientTo: '#ECFEFF',
    bgGradientAngle: 'to-br',
    textColor: '#581C87',
    headingColor: '#3B0764',
    linkHoverColor: '#9333EA',
    buttonColor: '#0891B2',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#0891B2',
    buttonStyle: 'gradient',
    buttonShape: 'pill',
    buttonHover: 'shimmer',
    cardStyle: 'glass',
    fontFamily: 'Sora',
    headingFont: 'Sora',
    bodyFont: 'Sora',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'minimal-dots',
  },

  // CATEGORY 5 — BOLD
  {
    id: 'onyx',
    name: 'Onyx',
    category: 'Bold',
    customizable: true,
    tagline: 'Absolute black and stark solid borders for maximum weight.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FFFFFF',
    bgGradientFrom: '#FFFFFF',
    bgGradientTo: '#F1F5F9',
    bgGradientAngle: 'to-b',
    textColor: '#0F172A',
    headingColor: '#000000',
    linkHoverColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#000000',
    buttonStyle: 'solid',
    buttonShape: 'sharp',
    buttonHover: 'lift',
    cardStyle: '3d',
    fontFamily: 'Space Grotesk',
    headingFont: 'Space Grotesk',
    bodyFont: 'Space Grotesk',
    baseSize: 16,
    fontWeight: 'bold',
    letterSpacing: 'tight',
    stickerPack: 'geometric',
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    category: 'Bold',
    customizable: true,
    tagline: 'Uncompromising 100% black on white with thick borders.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FFFFFF',
    bgGradientFrom: '#FFFFFF',
    bgGradientTo: '#FFFFFF',
    bgGradientAngle: 'to-b',
    textColor: '#000000',
    headingColor: '#000000',
    linkHoverColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#000000',
    buttonStyle: 'outline',
    buttonShape: 'sharp',
    buttonHover: 'underline',
    cardStyle: '3d',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'bold',
    letterSpacing: 'tight',
    stickerPack: 'geometric',
  },
  {
    id: 'editorial-bold',
    name: 'Editorial Bold',
    category: 'Bold',
    customizable: true,
    tagline: 'Classic black and white print layout using a serif typeface.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FDFBF7',
    bgGradientFrom: '#FDFBF7',
    bgGradientTo: '#F5F0E8',
    bgGradientAngle: 'to-b',
    textColor: '#1C1917',
    headingColor: '#0C0A09',
    linkHoverColor: '#78350F',
    buttonColor: '#0C0A09',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#0C0A09',
    buttonStyle: 'solid',
    buttonShape: 'pill',
    buttonHover: 'lift',
    cardStyle: '3d',
    fontFamily: 'Manrope',
    headingFont: 'Instrument Serif',
    bodyFont: 'Manrope',
    baseSize: 16,
    fontWeight: 'bold',
    letterSpacing: 'normal',
    stickerPack: 'subtle-lines',
  },
  {
    id: 'manifesto',
    name: 'Manifesto',
    category: 'Bold',
    customizable: true,
    tagline: 'Rebel text alignment with minimal container boundaries.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FAF5FF',
    bgGradientFrom: '#FAF5FF',
    bgGradientTo: '#F3E8FF',
    bgGradientAngle: 'to-b',
    textColor: '#3B0764',
    headingColor: '#2E1065',
    linkHoverColor: '#7E22CE',
    buttonColor: '#2E1065',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#2E1065',
    buttonStyle: 'solid',
    buttonShape: 'rounded',
    buttonHover: 'darken',
    cardStyle: 'minimal',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'bold',
    letterSpacing: 'tight',
    stickerPack: 'none',
  },

  // CATEGORY 6 — NATURE
  {
    id: 'sage',
    name: 'Sage',
    category: 'Nature',
    customizable: true,
    tagline: 'Quiet evergreen forest floors with deep leafy borders.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#F4F7F4',
    bgGradientFrom: '#F4F7F4',
    bgGradientTo: '#E8EFE8',
    bgGradientAngle: 'to-b',
    textColor: '#2D3E35',
    headingColor: '#1A2921',
    linkHoverColor: '#3F6253',
    buttonColor: '#1A2921',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#1A2921',
    buttonStyle: 'soft',
    buttonShape: 'rounded',
    buttonHover: 'lift',
    cardStyle: 'minimal',
    fontFamily: 'Manrope',
    headingFont: 'Manrope',
    bodyFont: 'Manrope',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'forest',
    name: 'Forest',
    category: 'Nature',
    customizable: true,
    tagline: 'Lush mossy canopy green transitioning into pine highlights.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#F0FDF4',
    bgGradientFrom: '#F0FDF4',
    bgGradientTo: '#DCFCE7',
    bgGradientAngle: 'to-b',
    textColor: '#14532D',
    headingColor: '#052E16',
    linkHoverColor: '#15803D',
    buttonColor: '#052E16',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#052E16',
    buttonStyle: 'solid',
    buttonShape: 'rounded',
    buttonHover: 'lift',
    cardStyle: 'elevated',
    fontFamily: 'DM Sans',
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'minimal-dots',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    category: 'Nature',
    customizable: true,
    tagline: 'Breezy shoreline gradients with translucent surf elements.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#F0FDFA',
    bgGradientFrom: '#F0FDFA',
    bgGradientTo: '#E0F2FE',
    bgGradientAngle: 'to-br',
    textColor: '#115E59',
    headingColor: '#0F766E',
    linkHoverColor: '#0284C7',
    buttonColor: '#0C4A6E',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#0C4A6E',
    buttonStyle: 'glass',
    buttonShape: 'pill',
    buttonHover: 'glass',
    cardStyle: 'glass',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'dune',
    name: 'Dune',
    category: 'Nature',
    customizable: true,
    tagline: 'Windswept Sahara sand gradients and camel leather tags.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#FAF6F0',
    bgGradientFrom: '#FAF6F0',
    bgGradientTo: '#F0E6D8',
    bgGradientAngle: 'to-b',
    textColor: '#4A3B32',
    headingColor: '#2D221C',
    linkHoverColor: '#92400E',
    buttonColor: '#8C5A3C',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#8C5A3C',
    buttonStyle: 'solid',
    buttonShape: 'pill',
    buttonHover: 'lift',
    cardStyle: 'minimal',
    fontFamily: 'Sora',
    headingFont: 'Sora',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'normal',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },

  // CATEGORY 7 — DARK PREMIUM
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'Dark',
    customizable: true,
    tagline: 'Extremely deep near-black cosmic backdrop with crisp white pills.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#0B1220',
    bgGradientFrom: '#0B1220',
    bgGradientTo: '#0B1220',
    bgGradientAngle: 'to-b',
    textColor: '#94A3B8',
    headingColor: '#FFFFFF',
    linkHoverColor: '#FFFFFF',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#0F172A',
    buttonBorderColor: '#FFFFFF',
    buttonStyle: 'solid',
    buttonShape: 'pill',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    category: 'Dark',
    customizable: true,
    tagline: 'Deep navy background lit up by modern electric blue badges.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#030712',
    bgGradientFrom: '#030712',
    bgGradientTo: '#0B1530',
    bgGradientAngle: 'to-b',
    textColor: '#94A3B8',
    headingColor: '#FFFFFF',
    linkHoverColor: '#38BDF8',
    buttonColor: '#1E40AF',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#3B82F6',
    buttonStyle: 'glow',
    buttonShape: 'rounded',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    category: 'Dark',
    customizable: true,
    tagline: 'Sooty industrial gray base using clean outlined components.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#18181B',
    bgGradientFrom: '#18181B',
    bgGradientTo: '#18181B',
    bgGradientAngle: 'to-b',
    textColor: '#A1A1AA',
    headingColor: '#FAFAFA',
    linkHoverColor: '#FAFAFA',
    buttonColor: '#27272A',
    buttonTextColor: '#FAFAFA',
    buttonBorderColor: '#3F3F46',
    buttonStyle: 'outline',
    buttonShape: 'rounded',
    buttonHover: 'lift',
    cardStyle: 'minimal',
    fontFamily: 'DM Sans',
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'night-gold',
    name: 'Night Gold',
    category: 'Dark',
    customizable: true,
    tagline: 'Opulent obsidian canvas matched with rich, glowing gold buttons.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#09090B',
    bgGradientFrom: '#09090B',
    bgGradientTo: '#18181B',
    bgGradientAngle: 'to-b',
    textColor: '#D4D4D8',
    headingColor: '#F59E0B',
    linkHoverColor: '#FBBF24',
    buttonColor: '#F59E0B',
    buttonTextColor: '#09090B',
    buttonBorderColor: '#F59E0B',
    buttonStyle: 'gradient',
    buttonShape: 'pill',
    buttonHover: 'shimmer',
    cardStyle: 'elevated',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'subtle-lines',
  },

  // CATEGORY 8 — GLASS / GLOSSY
  {
    id: 'frosted-glass',
    name: 'Frosted Glass',
    category: 'Glass',
    customizable: true,
    tagline: 'High blur, translucent white card over a beautiful sunset pastel.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#F5F3FF',
    bgGradientFrom: '#F5F3FF',
    bgGradientTo: '#FFF1F2',
    bgGradientAngle: 'to-br',
    textColor: '#4C1D95',
    headingColor: '#2E1065',
    linkHoverColor: '#9061F9',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#2E1065',
    buttonBorderColor: '#E4E4E7',
    buttonStyle: 'glass',
    buttonShape: 'rounded',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'liquid-glass',
    name: 'Liquid Glass',
    category: 'Glass',
    customizable: true,
    tagline: 'Hyper-glossy organic gradient with a high-shine glassy border.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#E0F2FE',
    bgGradientFrom: '#E0F2FE',
    bgGradientTo: '#F5F3FF',
    bgGradientAngle: 'to-tr',
    textColor: '#0369A1',
    headingColor: '#075985',
    linkHoverColor: '#0284C7',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#075985',
    buttonBorderColor: '#BAE6FD',
    buttonStyle: 'glass',
    buttonShape: 'pill',
    buttonHover: 'shimmer',
    cardStyle: 'glass',
    fontFamily: 'Manrope',
    headingFont: 'Manrope',
    bodyFont: 'Manrope',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'crystal-clear',
    name: 'Crystal Clear',
    category: 'Glass',
    customizable: true,
    tagline: 'Ultra-thin, nearly transparent glass panels over fine silk gradient.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#EFF6FF',
    bgGradientFrom: '#EFF6FF',
    bgGradientTo: '#F5F3FF',
    bgGradientAngle: 'to-b',
    textColor: '#1E40AF',
    headingColor: '#1E3A8A',
    linkHoverColor: '#3B82F6',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#1E3A8A',
    buttonBorderColor: '#BFDBFE',
    buttonStyle: 'glass',
    buttonShape: 'rounded',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Sora',
    headingFont: 'Sora',
    bodyFont: 'Sora',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'smoke-glass',
    name: 'Smoke Glass',
    category: 'Glass',
    customizable: true,
    tagline: 'Velvety gray smoke and mist backdrops overlaid with frost blocks.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#F1F5F9',
    bgGradientFrom: '#F1F5F9',
    bgGradientTo: '#E2E8F0',
    bgGradientAngle: 'to-br',
    textColor: '#475569',
    headingColor: '#1E293B',
    linkHoverColor: '#0F172A',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#1E293B',
    buttonBorderColor: '#CBD5E1',
    buttonStyle: 'glass',
    buttonShape: 'rounded',
    buttonHover: 'glass',
    cardStyle: 'glass',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },

  // CATEGORY 9 — GLOW / NEON
  {
    id: 'neon-violet',
    name: 'Neon Violet',
    category: 'Glow',
    customizable: true,
    tagline: 'Pulsing purple neon glow borders over standard darkness.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#0F091A',
    bgGradientFrom: '#0F091A',
    bgGradientTo: '#0F091A',
    bgGradientAngle: 'to-b',
    textColor: '#C084FC',
    headingColor: '#A855F7',
    linkHoverColor: '#E9D5FF',
    buttonColor: '#A855F7',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#A855F7',
    buttonStyle: 'glow',
    buttonShape: 'pill',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Space Grotesk',
    headingFont: 'Space Grotesk',
    bodyFont: 'Space Grotesk',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'cyber-lime',
    name: 'Cyber Lime',
    category: 'Glow',
    customizable: true,
    tagline: 'Ultra high-contrast lime green glowing action items.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#05070A',
    bgGradientFrom: '#05070A',
    bgGradientTo: '#05070A',
    bgGradientAngle: 'to-b',
    textColor: '#A3E635',
    headingColor: '#84CC16',
    linkHoverColor: '#BEF264',
    buttonColor: '#84CC16',
    buttonTextColor: '#000000',
    buttonBorderColor: '#84CC16',
    buttonStyle: 'glow',
    buttonShape: 'rounded',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Sora',
    headingFont: 'Sora',
    bodyFont: 'Sora',
    baseSize: 16,
    fontWeight: 'bold',
    letterSpacing: 'tight',
    stickerPack: 'none',
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue',
    category: 'Glow',
    customizable: true,
    tagline: 'Pure electric blue neon laser glow illuminating the profile.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#020617',
    bgGradientFrom: '#020617',
    bgGradientTo: '#020617',
    bgGradientAngle: 'to-b',
    textColor: '#38BDF8',
    headingColor: '#0EA5E9',
    linkHoverColor: '#7DD3FC',
    buttonColor: '#0EA5E9',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#0EA5E9',
    buttonStyle: 'glow',
    buttonShape: 'pill',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'magenta-pulse',
    name: 'Magenta Pulse',
    category: 'Glow',
    customizable: true,
    tagline: 'High frequency magenta glow lines on dark velvet base.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#0F050C',
    bgGradientFrom: '#0F050C',
    bgGradientTo: '#0F050C',
    bgGradientAngle: 'to-b',
    textColor: '#F472B6',
    headingColor: '#EC4899',
    linkHoverColor: '#FBCFE8',
    buttonColor: '#EC4899',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#EC4899',
    buttonStyle: 'glow',
    buttonShape: 'rounded',
    buttonHover: 'shimmer',
    cardStyle: 'glass',
    fontFamily: 'Manrope',
    headingFont: 'Manrope',
    bodyFont: 'Manrope',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },

  // CATEGORY 10 — 3D / GRAVITY
  {
    id: 'depth',
    name: 'Depth',
    category: '3D',
    customizable: true,
    tagline: 'Layered retro-futuristic isometric button shadows.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FFFFFF',
    bgGradientFrom: '#FFFFFF',
    bgGradientTo: '#F8FAFC',
    bgGradientAngle: 'to-b',
    textColor: '#1E293B',
    headingColor: '#0F172A',
    linkHoverColor: '#2563EB',
    buttonColor: '#2563EB',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#1E293B',
    buttonStyle: 'shadow',
    buttonShape: 'rounded',
    buttonHover: 'lift',
    cardStyle: '3d',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'gravity',
    name: 'Gravity',
    category: '3D',
    customizable: true,
    tagline: 'Floating pill containers hanging over cool shadows.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#F1F5F9',
    bgGradientFrom: '#F1F5F9',
    bgGradientTo: '#F1F5F9',
    bgGradientAngle: 'to-b',
    textColor: '#334155',
    headingColor: '#0F172A',
    linkHoverColor: '#475569',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#0F172A',
    buttonBorderColor: '#E2E8F0',
    buttonStyle: 'shadow',
    buttonShape: 'pill',
    buttonHover: 'lift',
    cardStyle: '3d',
    fontFamily: 'DM Sans',
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'pop-3d',
    name: 'Pop 3D',
    category: '3D',
    customizable: true,
    tagline: 'Bold comic book aesthetic with thick offset block shadows.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FFFBEB',
    bgGradientFrom: '#FFFBEB',
    bgGradientTo: '#FFFBEB',
    bgGradientAngle: 'to-b',
    textColor: '#000000',
    headingColor: '#000000',
    linkHoverColor: '#F59E0B',
    buttonColor: '#F59E0B',
    buttonTextColor: '#000000',
    buttonBorderColor: '#000000',
    buttonStyle: 'shadow',
    buttonShape: 'rounded',
    buttonHover: 'lift',
    cardStyle: '3d',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'bold',
    letterSpacing: 'tight',
    stickerPack: 'geometric',
  },
  {
    id: 'floating-cards',
    name: 'Floating Cards',
    category: '3D',
    customizable: true,
    tagline: 'Floating glass tiles suspended over ambient neon lights.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#EFF6FF',
    bgGradientFrom: '#EFF6FF',
    bgGradientTo: '#F5F3FF',
    bgGradientAngle: 'to-br',
    textColor: '#1E40AF',
    headingColor: '#1E3A8A',
    linkHoverColor: '#2563EB',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#1E3A8A',
    buttonBorderColor: '#DBEAFE',
    buttonStyle: 'glass',
    buttonShape: 'pill',
    buttonHover: 'glass',
    cardStyle: '3d',
    fontFamily: 'Sora',
    headingFont: 'Sora',
    bodyFont: 'Sora',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },

  // CATEGORY 11 — METALLIC
  {
    id: 'chrome-metal',
    name: 'Chrome',
    category: 'Metallic',
    customizable: true,
    tagline: 'Brushed chrome silver actions with reflective glow accents.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#F1F5F9',
    bgGradientFrom: '#E2E8F0',
    bgGradientTo: '#CBD5E1',
    bgGradientAngle: 'to-b',
    textColor: '#1E293B',
    headingColor: '#0F172A',
    linkHoverColor: '#334155',
    buttonColor: '#94A3B8',
    buttonTextColor: '#000000',
    buttonBorderColor: '#E2E8F0',
    buttonStyle: 'gradient',
    buttonShape: 'pill',
    buttonHover: 'glow',
    cardStyle: 'minimal',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'gold-foil',
    name: 'Gold Foil',
    category: 'Metallic',
    customizable: true,
    tagline: 'Reflective gold metallic foil gradient matched with dark ink.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FFFDF5',
    bgGradientFrom: '#FFFDF5',
    bgGradientTo: '#FFFDF5',
    bgGradientAngle: 'to-b',
    textColor: '#78350F',
    headingColor: '#451A03',
    linkHoverColor: '#B45309',
    buttonColor: '#D97706',
    buttonTextColor: '#1A0D00',
    buttonBorderColor: '#D97706',
    buttonStyle: 'gradient',
    buttonShape: 'rounded',
    buttonHover: 'shimmer',
    cardStyle: 'elevated',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'bold',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    category: 'Metallic',
    customizable: true,
    tagline: 'Modern rose-tinted copper glow on polished slate canvas.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#FFF1F2',
    bgGradientFrom: '#FFF1F2',
    bgGradientTo: '#FFE4E6',
    bgGradientAngle: 'to-b',
    textColor: '#881337',
    headingColor: '#4C0519',
    linkHoverColor: '#E11D48',
    buttonColor: '#FDA4AF',
    buttonTextColor: '#4C0519',
    buttonBorderColor: '#FDA4AF',
    buttonStyle: 'gradient',
    buttonShape: 'pill',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Sora',
    headingFont: 'Sora',
    bodyFont: 'Sora',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
  {
    id: 'platinum-metal',
    name: 'Platinum',
    category: 'Metallic',
    customizable: true,
    tagline: 'Prestigious pale platinum action points on clean background.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FAFAFA',
    bgGradientFrom: '#FAFAFA',
    bgGradientTo: '#F4F4F5',
    bgGradientAngle: 'to-b',
    textColor: '#27272A',
    headingColor: '#09090B',
    linkHoverColor: '#3F3F46',
    buttonColor: '#E4E4E7',
    buttonTextColor: '#09090B',
    buttonBorderColor: '#E4E4E7',
    buttonStyle: 'solid',
    buttonShape: 'rounded',
    buttonHover: 'lift',
    cardStyle: 'minimal',
    fontFamily: 'Manrope',
    headingFont: 'Manrope',
    bodyFont: 'Manrope',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'tight',
    stickerPack: 'none',
  },

  // CATEGORY 12 — CURATED (NON-CUSTOMIZABLE)
  {
    id: 'vault-signature',
    name: 'Vault Signature',
    category: 'Curated',
    customizable: false,
    tagline: 'LinkVM flagship signature theme with vivid indigo actions.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#EEF2FF',
    bgGradientFrom: '#EEF2FF',
    bgGradientTo: '#E0E7FF',
    bgGradientAngle: 'to-br',
    textColor: '#1E1B4B',
    headingColor: '#4F46E5',
    linkHoverColor: '#6366F1',
    buttonColor: '#4F46E5',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#4F46E5',
    buttonStyle: 'solid',
    buttonShape: 'pill',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'bold',
    letterSpacing: 'normal',
    stickerPack: 'geometric',
  },
  {
    id: 'marble-luxe',
    name: 'Marble Luxe',
    category: 'Curated',
    customizable: false,
    tagline: 'Beautiful marble white canvas and sleek slate grey actions.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#FDFBF7',
    bgGradientFrom: '#FDFBF7',
    bgGradientTo: '#ECE7E1',
    bgGradientAngle: 'to-b',
    textColor: '#1E293B',
    headingColor: '#0F172A',
    linkHoverColor: '#64748B',
    buttonColor: '#FFFFFF',
    buttonTextColor: '#1E293B',
    buttonBorderColor: '#CBD5E1',
    buttonStyle: 'glass',
    buttonShape: 'pill',
    buttonHover: 'glass',
    cardStyle: 'glass',
    fontFamily: 'Inter',
    headingFont: 'Inter',
    bodyFont: 'DM Sans',
    baseSize: 16,
    fontWeight: 'medium',
    letterSpacing: 'tight',
    stickerPack: 'subtle-lines',
  },
  {
    id: 'obsidian-ink-curated',
    name: 'Obsidian Ink',
    category: 'Curated',
    customizable: false,
    tagline: 'Near-white luxury paper contrasted with rich velvet ink pillars.',
    badge: 'Premium · Free Forever',
    bgType: 'solid',
    bgColor: '#F8FAFC',
    bgGradientFrom: '#F8FAFC',
    bgGradientTo: '#E2E8F0',
    bgGradientAngle: 'to-b',
    textColor: '#09090B',
    headingColor: '#000000',
    linkHoverColor: '#18181B',
    buttonColor: '#09090B',
    buttonTextColor: '#FAFAFA',
    buttonBorderColor: '#09090B',
    buttonStyle: 'solid',
    buttonShape: 'sharp',
    buttonHover: 'lift',
    cardStyle: '3d',
    fontFamily: 'Plus Jakarta Sans',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    baseSize: 16,
    fontWeight: 'bold',
    letterSpacing: 'tight',
    stickerPack: 'geometric',
  },
  {
    id: 'aurora-luxe',
    name: 'Aurora Luxe',
    category: 'Curated',
    customizable: false,
    tagline: 'Glistening boreal lights overlaid with ultra blurred frosted pills.',
    badge: 'Premium · Free Forever',
    bgType: 'gradient',
    bgColor: '#F5F3FF',
    bgGradientFrom: '#F5F3FF',
    bgGradientTo: '#DCFCE7',
    bgGradientAngle: 'to-tr',
    textColor: '#4C1D95',
    headingColor: '#2E1065',
    linkHoverColor: '#7C3AED',
    buttonColor: '#7C3AED',
    buttonTextColor: '#FFFFFF',
    buttonBorderColor: '#7C3AED',
    buttonStyle: 'glass',
    buttonShape: 'rounded',
    buttonHover: 'glow',
    cardStyle: 'glass',
    fontFamily: 'Manrope',
    headingFont: 'Manrope',
    bodyFont: 'Inter',
    baseSize: 16,
    fontWeight: 'semibold',
    letterSpacing: 'normal',
    stickerPack: 'none',
  },
];

export const DEFAULT_THEME: ThemePreset = THEME_PRESETS[0];

export const THEME_CATEGORIES = [
  'All',
  '3D',
  'Glow',
  'Glass',
  'Dark',
  'Metallic',
  'Gradient',
  'Curated',
  'Cool',
  'Warm',
  'Nature',
  'Bold',
  'Minimal',
] as const;

// Programmatically assign signature to all preset objects
THEME_PRESETS.forEach((theme) => {
  if (theme.category === '3D') theme.signature = '3d';
  else if (theme.category === 'Glow') theme.signature = 'glow';
  else if (theme.category === 'Glass') theme.signature = 'glass';
  else if (theme.category === 'Dark') theme.signature = 'dark';
  else if (theme.category === 'Gradient') theme.signature = 'gradient';
  else if (theme.category === 'Metallic') theme.signature = 'metallic';
  else if (theme.id === 'aurora-luxe') theme.signature = 'glass';
  else theme.signature = 'flat';
});

export function presetToConfig(preset: ThemePreset, userId = ''): ThemeConfig {
  return {
    id: `theme_${preset.id}`,
    userId,
    presetId: preset.id,
    category: preset.category,
    customizable: preset.customizable,
    tagline: preset.tagline,
    badge: preset.badge,
    bgColor: preset.bgColor,
    bgGradientFrom: preset.bgGradientFrom || null,
    bgGradientTo: preset.bgGradientTo || null,
    bgGradientAngle: preset.bgGradientAngle || null,
    bgType: preset.bgType,
    textColor: preset.textColor,
    headingColor: preset.headingColor,
    linkHoverColor: preset.linkHoverColor,
    buttonColor: preset.buttonColor,
    buttonTextColor: preset.buttonTextColor,
    buttonBorderColor: preset.buttonBorderColor,
    buttonStyle: preset.buttonStyle,
    buttonShape: preset.buttonShape,
    buttonHover: preset.buttonHover,
    cardStyle: preset.cardStyle,
    fontFamily: preset.fontFamily,
    headingFont: preset.headingFont,
    bodyFont: preset.bodyFont,
    baseSize: preset.baseSize,
    fontWeight: preset.fontWeight,
    letterSpacing: preset.letterSpacing,
    stickerPack: preset.stickerPack,
    socialIconSize: preset.socialIconSize || 'medium',
    socialIconShape: preset.socialIconShape || 'circle',
    socialIconFill: preset.socialIconFill || 'outline',
    socialIconColor: preset.socialIconColor || '#0F172A',
    socialIconBg: preset.socialIconBg || '#FFFFFF',
    socialIconBorder: preset.socialIconBorder || '#E2E8F0',
    socialIconSpacing: preset.socialIconSpacing || 'normal',
    socialIconLayout: preset.socialIconLayout || 'row',
    socialIconAlign: preset.socialIconAlign || 'center',
    signature: preset.signature || 'flat',
    updatedAt: new Date().toISOString(),
  };
}
